image: registry.gitlab.com/wylieyyyy/shellfront:latest

stages:
    - build
    - make
    - test

build-pkg:
    stage: build
    script:
        - rm -rf .git
        - autoreconf -i
    after_script:
        - Xvfb :1 -screen 0 1600x1200x24 &
        - export DISPLAY=:1
    artifacts:
        paths:
            - "*"

make-pkg:
    stage: make
    script:
        - ./configure
        - make

test:
    stage: test
    script:
        - ./configure --enable-unit-tests
        - make
        - src/test
        - gcovr -e 'src/t_*' -r src --branches
