image: registry.gitlab.com/wylieyyyy/shellfront:latest

stages:
    - build
    - test

build-pkg:
    stage: build
    script:
        - autoreconf -i
    artifacts:
        paths:
            - "*"

make-pkg:
    stage: build
    script:
        - ./configure
        - make

test:
    stage: test
    script:
        - ./configure --enable-unit-tests
        - make
        - src/test
        - gcovr -r src --branches
