image: registry.gitlab.com/wylieyyyy/shellfront:latest

stages:
    - build
    - make
    - test

default:
    before_script:
        - Xvfb :1 -screen 0 1600x1200x24 &
        - export DISPLAY=:1
        - export SHELL=/bin/bash

build:
    stage: build
    script:
        - rm -rf .git
        - autoreconf -i
    artifacts:
        paths:
            - "*"

make:
    stage: make
    script:
        - ./configure
        - make

test:
    stage: test
    script:
        - ./configure --enable-unit-tests
        - make
        - src/test
        - gcovr -e 'src/t_*' -r src
