image: registry.gitlab.com/wylieyyyy/shellfront:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - autoreconf -i
        - ./configure
        - make

test:
    stage: test
    script:
        - make clean
        - ./configure --enable-unit-tests
        - make
        - src/test
        - gcovr -r src --branches
